NatLibFi/NDL-VuFind2

module/Finna/src/Finna/Controller/PrimoController.php
=> [ALLI-3348] Bug fix: show results from Primo when the search is started from Primo/Home

local/config/vufind/rss.ini, module/Finna/src/Finna/Controller/AjaxController.php
…nt link label on touch devices and desktops.
=> Add configuration option for specifying element link label on touch devices and desktops.

themes/custom/theme.config.php
Adds empty settings.css file to the custom theme for admin interface modifications.
=> Add settings.css file

local/config/vufind/permissions.ini, module/Finna/config/module.config.php, module/Finna/src/Finna/Role/PermissionProvider/AuthenticationStrategy.php, module/Finna/src/Finna/Role/PermissionProvider/Factory.php
(ILS stat code check missing for now).
=> [ALLI-3682] Check if user is authenticated using an authorizable strategy

themes/finna/templates/Recommend/SideFacets.phtml
…ain level is selected and closed
=> Open hierarchies if less than 3 main level elements or hierarchical main level is selected

module/Finna/src/Finna/Search/Minified.php, module/FinnaConsole/src/FinnaConsole/Controller/UtilController.php, themes/finna/templates/Email/scheduled-alert.phtml, themes/finna/templates/RecordDriver/SolrDefault/result-email.phtml, themes/finna/templates/RecordDriver/SolrEad/result-email.phtml, themes/finna/templates/RecordDriver/SolrLido/result-email.phtml
- Deminify saved searches using VuFind and Finna search objects.
- Manually add daterange filter when required.
- Use filter display text in emails.
- Tweak line breaks in emails.
=> [ALLI-3711] Fix problems in sending scheduled alerts.

module/Finna/src/Finna/Controller/SearchController.php
Browse database/journal actions.
=> [ALLI-3923] Prevent selected result view option from being overridden by

module/Finna/config/module.config.php, module/Finna/src/Finna/Service/Factory.php, module/FinnaConsole/src/FinnaConsole/Controller/UtilController.php
- Handle saved searches without finna_search_object.
- Do not attempt to use cookies while in console mode.
- Catch exception from Mailer.
=> [ALLI-3711] Fix problems with processing scheduled alerts.

module/Finna/config/module.config.php
Remove similar items and description.
=> [ALLI-3734] Re-configure SolrDefault record tabs.

module/Finna/src/Finna/Cover/Loader.php
see: ebabd572a9b55aa0278bde0f79644abc1c3eb1a7
=> Update Cover loader with upstream changes.

local/httpd-vufind.conf.sample, module/Finna/src/Finna/View/Helper/Root/Factory.php, module/Finna/src/Finna/View/Helper/Root/FileSrc.php, themes/finna/theme.config.php
=> [ALLI-3947] Add view helper for resolving path to a resource in theme

module/Finna/src/Finna/Controller/SearchApiController.php
- Remove comments-field.
- Drop summary-field for Marc-records.
=> [ALLI-4064] [ALLI-4063] API improvements

local/config/finna/MetaLib.ini.sample, module/Finna/src/Finna/View/Helper/Root/Autocomplete.php, themes/finna/templates/layout/layout.phtml, themes/finna/templates/search/searchbox.phtml
=> [ALLI-4138] Fix bug in displaying autocomplete filters on search home

local/config/finna/searches.ini.sample, module/Finna/src/Finna/Autocomplete/Solr.php
- Fix a bug where only the last configured facet option for a field was
used.
- Allow facet value filtering based on a single value (previously a list of
values).
=> [ALLI-4143] Bug fixes and changes to autocomplete faceting.

local/config/vufind/config.ini.sample
Cleaned up the config.ini.sample a bit and commented out the url for the [piwik] section, since the URL is defined in the parent config in normal cases.
=> Clean up config.ini sample

module/Finna/src/Finna/RecordDriver/SolrQdc.php, themes/finna/templates/RecordDriver/SolrDefault/result-online-urls.phtml, themes/finna/templates/record/record-organisation-menu.phtml
- Attempt to find record image URL from file::href-attribute.
- Show name of providing organization on record page.
- Improve logic when to show "Available online" text in search results.
=> DC-record driver improvements.

module/FinnaConsole/Module.php, module/FinnaConsole/config/module.config.php, module/FinnaConsole/src/FinnaConsole/Controller/UtilController.php, module/FinnaConsole/src/FinnaConsole/Service/EncryptCatalogPasswords.php, module/FinnaConsole/src/FinnaConsole/Service/Factory.php
Since this is a manually executed utility, it logs output directly to console.
=> Added a console utility for encrypting ILS catalog passwords.

module/Finna/src/Finna/Controller/MyResearchController.php
Note: this commit depends on PR 381 (https://github.com/NatLibFi/NDL-VuFind2/pull/381)
=> [ALLI-4263] Add support for unsubscribing due date reminders.

local/config/finna/config.ini.sample, module/Finna/src/Finna/View/Helper/Root/HoldingsSettings.php, themes/finna/templates/ajax/status-full.phtml
- Override Voyager sort order and re-sort by availability and location.
- Configure item limit for truncating holdings.
=> [ALLI-4272] Add configuration options for Voyager holdings.

themes/finna/templates/Recommend/SideFacets.phtml, themes/finna/templates/Recommend/SideFacetsDeferred.phtml
(Commit has wrong task number, pull request correct one.)
=> [ALLI-4346] Possibility to add html to checkbox facet labels.

themes/finna/templates/RecordDriver/SolrDefault/list-entry.phtml
=> [ALLI-4422] fix image scaling in myresearch favorites

themes/finna/templates/layout/layout.phtml
[ALLI-2121] Turn off automatic telephone number detection on iOS.
=> Turn off automatic telephone number detection on iOS

local/languages/finna/fi.ini
Oiva, Krannit, Ilmajoki, Lakia, Seitti, Yty
=> Translations for Seitti etc fi

module/Finna/src/Finna/OrganisationInfo/OrganisationInfo.php, themes/finna/js/finna-organisation-info-page-consortium.js, themes/finna/js/finna-organisation-info-page.js, themes/finna/templates/organisationinfo/home.phtml
- Remove debug logging.
- Fix js-initialization parameter.
- Hide "Show all on map" link when only one library is available.
- Fix hiding logic for office info and usage info loaders.
=> Organisation info fixes.

themes/finna/js/finna-organisation-info-widget.js
default service point is not defined.
=> [ALLI-4735] Display first organisation in info widget when default service point is not defined.

themes/finna/templates/RecordDriver/EDS/result-list.phtml, themes/finna/templates/RecordDriver/Primo/result-list.phtml
=> [ALLI-5071] Fix for bulk options' checkbox

module/Finna/src/Finna/Resolver/Driver/Factory.php, module/Finna/src/Finna/Resolver/Driver/Sfx.php
Use timeout from config.ini if timeout is set. Default timeout is 30.
=> [ALLI-5003] Sfx resolver error

module/Finna/src/Finna/RecordDriver/SolrLido.php
Added missing opening bracket in code to show row correctly in record.
=> [ALLI-4826] Other classification fix

local/languages/finna/en-gb.ini, local/languages/finna/fi.ini, local/languages/finna/sv.ini
Translation for suunnittelu and fixed a little bit of alphabetical order.
=> Translation for lido_event_type_Document_suunnittelu

local/languages/finna/en-gb.ini, local/languages/finna/fi.ini, local/languages/finna/sv.ini
https://foorumi.kiwi.fi/t/saatavissa-oleva-aineisto-joka-ei-ole-saatavissa/773
=> Modified translation for status_Withdrawn

module/Finna/src/Finna/RecordDriver/SolrLido.php
=> Show LIDO photographer information on all lido-records..

module/Finna/src/Finna/ILS/Driver/Mikromarc.php, themes/finna2/templates/RecordTab/holdingsils.phtml
=> [ALLI-5582] Fix for Mikromarc driver holding status visibility

module/Finna/src/Finna/ILS/Driver/Mikromarc.php
Other things in jira task can be solved with editing settings for organisation.
=> [ALLI-5598] Added totalItems counter to Mikromarc

module/Finna/src/Finna/ILS/Driver/Mikromarc.php
=> [ALLI-5620] Add check/translation for missing error code

themes/finna2/templates/librarycards/editcard.phtml, themes/finna2/templates/librarycards/newpassword.phtml, themes/finna2/templates/myresearch/cataloglogin.phtml
Fixes a problem where vertical menu was rendered when not needed
=> Vertical menu context fix

themes/finna2/less/finna/myresearch.less
Fixes the caret position to center if parent is 2 or more rows long
=> Vertical menu caret fix

themes/finna2/less/finna-variables.less, themes/finna2/less/finna/navigation.less
Login button was too close to the hamburger icon in smaller than 991px screens.
=> Better positioning for login options button

themes/finna2/templates/search/searchbox.phtml
Rajaa hakua valikkoa pystyy nyt selaamaan tabulaattorilla.
=> [Alli-5603] Searchfield dropdown focus fix

themes/finna2/less/finna-variables.less, themes/finna2/less/finna/navigation.less
Navibar account menu no longer goes out of the screen in smaller than 400px screens. Adjusted the position of login and logout options buttons.
=> Navibar account menu positioning improvements

themes/finna2/js/finna-mylist.js, themes/finna2/less/finna/mylist.less, themes/finna2/less/finna/tabs.less
Changes the position of remove favorite list popup to center of screen, finna-main-tabs container should no longer break the view, adds font-weight to vertical menu titles
=> Myresearch page improvements

themes/finna2/templates/navibar.phtml
Changes the place of saved searches and favorites in navibar dropdown menu
=> Changes the position of 2 dropdown menu items in navibar

themes/finna2/less/finna/filters.less, themes/finna2/less/finna/forms.less, themes/finna2/less/finna/result-sidebar.less, themes/finna2/less/finna/searchbox.less, themes/finna2/templates/search/filters.phtml
Changes the style of checkboxes for accessibility.
=> [Alli-5606] Accessible checkbox

module/Finna/src/Finna/Controller/ListController.php, themes/finna2/less/finna/public-favorites.less, themes/finna2/templates/list/header.phtml, themes/finna2/templates/list/list.phtml
Hides the name of public lists creator because of gdpr.
=> [Alli-5642] Hide public list creator name

local/config/finna/Mikromarc.ini.sample, module/Finna/src/Finna/ILS/Driver/Mikromarc.php
=> [ALLI-5647] Added 'mobile' field to be changed as well when user changes phone number

themes/finna2/less/finna/finna-header.less, themes/finna2/less/finna/search.less, themes/finna2/templates/layout/layout.phtml, themes/finna2/templates/search/header.phtml
Adds a wrapper for .finna-main-header class so the color expands the whole page, adds a new less rule set .advanced-container for .search-form-container so they can be edited separately.
=> [Alli-5663] Search area background changes

themes/finna2/less/finna/library-cards.less, themes/finna2/less/finna/navigation.less, themes/finna2/templates/librarycards/selectcard.phtml
Adds a description for elements in dropdown menu and for the menu itself. Removes unnecessary part of less.
=> [Alli-5648] Selectcard template accessibility

themes/finna2/less/finna/search.less, themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
Fixes the problem where user could not click a link in databases view, changes the icons of database entry and instruction links to an arrow as the check to assign proper icon was too inconsistent.
=> [Alli-5662] Browse database fixes

local/config/finna/facets.ini.sample
Uncomments the finna_geographic special facet from facets.ini.sample so admininterface can properly read it
=> [Alli-5671] Enable geographical subfacet for admininterface

themes/finna2/less/finna/searchbox.less
Fixes the background of non-home search tooltips.
=> Search tooltip background fix

themes/finna2/less/finna/record.less
Changes the width of large image layout to correspond its name
=> Large image layout width fix

local/languages/finna/en-gb.ini, local/languages/finna/fi.ini, local/languages/finna/sv.ini, themes/finna2/js/hierarchyTree.js, themes/finna2/less/finna/hierarchytree.less
Adds a notification inside archive structure popup, if there is no structure to display.
=> [Alli-5673] Empty archive notification

themes/finna2/js/finna-map.js, themes/finna2/templates/Recommend/SideFacets/geographic-facet.phtml, themes/finna2/templates/search/advanced/map.phtml, themes/finna2/templates/search/advanced/solr.phtml
Disables the map from screen readers and keyboards as it is designed for a mouse
=> [Alli-5605] Disable map search from screen reader and keyboard

themes/finna2/less/finna/searchbox.less
Adds margin top to link buttons under searchfield
=> [Alli-5705] Advanced search link button spacing

themes/finna2/templates/myresearch/newpassword.phtml
Removes the maintabs from the myresearch newpassword.phtml as it broke the page
=> [Alli-5728] Password recovery page fix

themes/finna2/js/finna-layout.js, themes/finna2/less/bootstrap.less
Fixes a problem where keyboard could not reach more / less / top links inside records, keeps focus on element after a click
=> [Alli-5706] More-, less- and top-link accessibility fix

module/Finna/src/Finna/AjaxHandler/GetFeed.php
Fixes the problem where feed links were not working on mobile devices
=> [Alli-5753] Fix mobile feeds

module/Finna/src/Finna/Controller/MyResearchController.php
Fixes the problem with success message when renewing checkedout items
=> [Alli-5756] Renewal max count fix

module/Finna/src/Finna/View/Helper/Root/HtmlElement.php
Adds a check to see if value can be escaped so the escaper doesn't throw an exception.
=> [Alli-5758] Htmlelement helper escape fix

themes/finna2/less/finna/myresearch.less
Pixels should no longer cause disturbance in the force.
=> [Alli-5761] Balance the pixels in myresearch page

themes/finna2/less/finna/feed.less, themes/finna2/less/finna/organisation-page.less
Also some feed grid style improvements
=> [Alli-6046] Fix xcal field styles in organisation info page

themes/finna2/less/finna/organisation-page.less, themes/finna2/templates/ajax/feed-list.phtml, themes/finna2/templates/feedcontent/content.phtml
Add "url" and "categories" xcal fields to content page & improve organisation info page event feed styles
=> Event feed fixes

module/Finna/src/Finna/RecordDriver/SolrForward.php
Depends on https://github.com/NatLibFi/RecordManager/pull/34
=> Change Forward authority linking to use updated record IDs.

themes/finna2/less/finna/video-player.less
Removed in https://github.com/NatLibFi/NDL-VuFind2/pull/1497
=> [ALLI-6210] Restore videojs player height

module/Finna/src/Finna/Controller/FeedbackController.php
Depends on: https://github.com/vufind-org/vufind/pull/1528
=> [ALLI-6223] FeedbackForms: fix redirect to form after external login

local/config/finna/OrganisationInfo.ini.sample, module/Finna/src/Finna/OrganisationInfo/OrganisationInfo.php
=> Handle kirkanta api version in OrganisationInfo.php instead of OrganisationInfo.ini

local/config/finna/FeedbackForms.yaml.sample
FeedbackController attempts to read 'email' post variable.
=> Fix record feedback form configuration so that reply-to is set to email sender

module/Finna/src/Finna/OrganisationInfo/OrganisationInfo.php
testailussa organisaatioksi esim. Lukki
=> [ALLI-6349] Fix organisation schedule daily info

module/Finna/src/Finna/Controller/CoverController.php, themes/finna2/js/finna-layout.js
Fixes a bug introduced in:
https://github.com/NatLibFi/NDL-VuFind2/commit/d3a32c23b95acf4da4fadb3d571ca2c431027caf
=> Cover loader: validate size only when given

module/Finna/src/Finna/OrganisationInfo/OrganisationInfo.php, themes/finna2/js/finna-organisation-info-page.js, themes/finna2/js/finna-organisation-info-widget.js, themes/finna2/js/finna-organisation-info.js, themes/finna2/less/finna/organisation-page.less, themes/finna2/templates/Helpers/organisation-info-contacts.phtml, themes/finna2/templates/Helpers/organisation-info-email-page.phtml, themes/finna2/templates/Helpers/organisation-info-email-widget.phtml, themes/finna2/templates/Helpers/organisation-info.phtml
Testailussa esim. Helmet. Oodilla useampi sähköpostiosoite
=> [Alli-6417] List all library email addresses in organisation info page & widget

themes/finna2/templates/RecordDriver/DefaultRecord/toolbar_mobile.phtml
- Change the order of action buttons on sticky toolbar. Basically just moved position of the "share" action button.
=> [ALLI-6460] sticky toolbar mobile fixes

themes/finna2/less/finna/mylist.less
- Make sure that favourites selector stays visible and readable on mobile.
=> [ALLI-6459] favourites selector mobile fixes

module/Finna/src/Finna/Controller/ListController.php, module/Finna/src/Finna/View/Helper/Root/UserListEmbed.php, module/Finna/src/Finna/View/Helper/Root/UserListEmbedFactory.php, themes/finna2/less/finna/mylist.less, themes/finna2/templates/Helpers/userlist.phtml, themes/finna2/templates/list/list.phtml
Suosikkilistojen tagitus konfiguroidaan:
`config.ini > Social > listTags = enabled`
Tagien näyttäminen upokkeessa:
`<?= $this->userlistEmbed(['id' => 123, 'tags' => true])?>`
=> [ALLI-6508] Add list tags to public list view and to list widget.
