NatLibFi/NDL-VuFind2

module/Finna/Module.php
When `limit_by_path` is set to `true` in `config.ini`, the bootstrap needs the the base url for session management before Finna module's onBoostrap is called. Thus we need to attach a callback with higher priority to bootstrap to ensure that the base url is set before it is requested.
=> Prioritize registration of base url

module/Finna/src/Finna/RecordDriver/Primo.php, module/Finna/src/Finna/RecordDriver/SolrFinna.php
Make sure that Finna's record image generator receives an array of parameters even when VuFind's record driver returns image URL as a string.
=> Make sure that Finna's record image generator receives an array of parameters even when VuFind's record driver returns image URL as a string.

themes/finna/js/finna-item-status.js, themes/finna/js/finna-layout.js, themes/finna/js/finna-search-tabs-recommendations.js, themes/finna/js/finna.js, themes/finna/templates/RecordDriver/SolrDefault/result-condensed.phtml, themes/finna/templates/RecordDriver/SolrEad/result-condensed.phtml, themes/finna/templates/RecordDriver/SolrLido/result-condensed.phtml, themes/finna/templates/RecordDriver/SolrQdc/result-condensed.phtml, themes/finna/templates/combined/results.phtml, themes/finna/templates/search/results.phtml, themes/finna/theme.config.php
- Load item statuses also when searchtabs recommendations are not enabled.
- Load item status in condensed view only when result item is expanded.
- Move record id attribute from "Save record" button to result item
container div in condensed result view so that the window scroll
position is restored when returning to search results from record page.
=> [ALLI-3287] Improvements to condensed result view.

module/Finna/src/Finna/View/Helper/Root/Factory.php, module/Finna/src/Finna/View/Helper/Root/SearchBox.php, themes/finna/templates/search/searchbox.phtml
- Use combined handlers only when search tabs are enabled.
- Bypass Combined/Searchbox in search form actions.
=> Fix search handler logic.

module/Finna/src/Finna/ILS/Connection.php
Fixes missing class 'ILSException' errors in connection.php on error.
=> Add missing use statement

module/Finna/src/Finna/Controller/AjaxController.php
Initializes the RSS reader http client using Vufind settings. By default, the rss reader uses a HTTP client with default settings, which causes SSL peer verification to fail due to lack of configured cafile/capath.
=> Initialize RSS reader http client

module/Finna/src/Finna/Cache/Manager.php
The cache directories were created with incorrect permission due to the the permissions being configured in the parent constructor, which was called after the caches were created.
=> Fix cache constructor execution order

module/Finna/src/Finna/Role/PermissionProvider/IpRange.php
Allows multiple comma separated ip ranges per range definition.
=> Allow comma separated ip ranges

module/Finna/sql/mysql.sql
The comments are saved by VuFind before the type is determined. Thus, the column needs a default value to prevent errors in strict sql mode.
=> Add default value for finna_type

module/Finna/src/Finna/View/Helper/Root/SearchTabs.php
Preserve 'type' URL parameter even when the selected handler
is not enabled. This is needed for autocomplete handlers to work
correctly when AllFields is the only enabled combined handler
(i.e. handler options are only shown in the autocomplete menu).
=> [ALLI-4132] Always preserve 'type' URL parameter.

themes/finna/templates/RecordDriver/SolrDefault/result-online-urls.phtml
(this partly reverts c8a1d1f3e6b95f8f3a164be1593ee8ed44ab191d)
=> Hide Available online -text from search results when only OpenURL links are  available

themes/finna/js/finna-metalib.js, themes/finna/templates/metalib/sidebar.phtml
- Disable MetaLib-tab click event when the tab is already active.
- Do not display notification of non-default (AllFields) search
handler when URL parameter type is undefined.
- Add check for '?' sign when appending search hash to URLs pointing
to other search tabs.
=> [ALLI-4273] [ALLI-4274] MetaLib fixes.

module/Finna/src/Finna/Controller/SearchController.php
- Use condensed result view even when it has not been enabled
for "normal" search results.
- Do not save the result type used in browsing to the search object.
=> [ALLI-4337] Fixes to database & journal browsing.

module/Finna/src/Finna/Controller/CoverController.php
Fixes to following notice, caused by the fact that you can't call `end()` with an expression:
Notice: Only variables should be passed by reference in /private/var/www/NDL-VuFind2/module/Finna/src/Finna/Controller/CoverController.php on line 90
=> Fix reference notice

module/Finna/src/Finna/View/Helper/Root/Navibar.php
Menu items were sorted only when the parent menu was also
positioned (i.e. only when __MENU__ = <pos> was found in navibar.ini).
=> Fix bug in sorting navigation menu items.

local/languages/finna/en-gb.ini, local/languages/finna/fi.ini, local/languages/finna/sv.ini
"Porstua on Kokkolan, Seinäjoen ja Vaasan kaupunginkirjasto-maakuntakirjastojen yhteistyön tulos", siksi tuo uusi nollatason fasetti
=> Translations for porstua

module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
AWS: Use the highest number of reservations for a single reservationqueue in oder to avoid inconsistencies.
=> AWS: Use the highest number of reservations

module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
[ALLI-4969] AWS: getMyHolds shows requestGroup (reginal and municipality holds) if it is enabled.
=> [ALLI-4969] AWS: getMyHolds shows requestGroup

module/Finna/src/Finna/RecordDriver/SolrLido.php, themes/finna/templates/RecordDriver/SolrLido/core.phtml
Added check for displaySubject, if found and it is different than the title of the record and it has label 'aihe' or no label at all, then it is shown below that said title. If not found or not usable then we will check description field and use that instead, if it is different than the title, if not then nothing is shown in summary field.
=> [ALLI-2985] Added getSummary to SolrLido.php

module/Finna/src/Finna/I18n/Translator/TranslatorAwareTrait.php
=> [ALLI-4963] Use wildcard translation key only when exact key is not defined.

themes/finna2/templates/myresearch/login.phtml
Tällä hetkellä tulostaa kaksi otsikkoa. Poistin toisen.
=> Remove duplicate login header

themes/finna2/js/finna-organisation-info-page.js
Was supposed to only hide from "contact details" -box and not below map
=> Fix for missing address below map in OrganisationInfo in museums

themes/finna2/less/finna/searchbox.less, themes/finna2/less/finna/tooltip.less, themes/finna2/templates/search/searchbox.phtml
Changes the search tooltip to be a button type element so the aria-describedby is being read properly by the screen readers. Hides the background image tooltip from screenreader and changes it to a button also. Cleaned a funky lookin part of code in searchbox.phtml.
=> [Alli-5604] Search tooltip accessibility fix

module/Finna/src/Finna/View/Helper/Root/HtmlElement.php
Put the check for empty boolean values to stringifyElement as the old way let empty values through if there were no template set for the html element.
=> HtmlElement empty boolean attribute fix

module/Finna/src/Finna/Controller/FeedContentController.php
Fixes the problem where feeds were not working properly on modals or new pages when the feed started with a capital letter
=> [Alli-5765] Feed uppercase name fix

themes/finna2/templates/RecordDriver/DefaultRecord/list-entry.phtml, themes/finna2/templates/RecordDriver/EDS/list-entry.phtml, themes/finna2/templates/RecordDriver/Primo/list-entry.phtml
Removes parts of list-entry.phtml as they are obsolete, caused an error and the other button wasn't working anymore.
=> Clean favorites list-entry templates

themes/finna2/less/bootstrap.less
- Hide the field until it has been initialized (prevents flashing that is caused by the field getting rendered before JS has been run).
- Set cursor of Show more/less buttons to pointer.
=> Fixes to truncated field.

module/FinnaConsole/src/FinnaConsole/Service/AccountExpirationReminders.php, module/FinnaConsole/src/FinnaConsole/Service/DueDateReminders.php, module/FinnaConsole/src/FinnaConsole/Service/Factory.php, module/FinnaConsole/src/FinnaConsole/Service/OnlinePaymentMonitor.php, module/FinnaConsole/src/FinnaConsole/Service/ScheduledAlerts.php
This prevents the connection to the SMTP server to time out even when the script takes a long time
to complete.
=> Rebuild VuFind\Mailer for each email to be sent.

themes/finna2/less/finna/feed.less, themes/finna2/less/finna/tabs.less, themes/finna2/templates/Helpers/feedtabs.phtml
This fixes a bug where "float: right" directive reversed the ordering of
the tab items.
=> Layout fix to FeedTabs helper.

module/Finna/src/Finna/Search/Solr/Params.php
=> Detect active author-id-role filter also when author2_id_role_str_mv

local/config/finna/facets.ini.sample
...so that the label works even when the facet is not enabled.
=> Configure extra facet label for author2_id_role_str_mv

module/Finna/src/Finna/Controller/SearchController.php
Formatting is performed in Solr/Params and SideFacets.
=> Remove unused call to AuthorityHelper facet formatting from SearchController.

module/Finna/src/Finna/Search/Solr/Params.php, themes/finna2/templates/Recommend/AuthorityRecommend.phtml
Korjaa bugin missä normaali Author-fasetti pääsi läpi `hasAuthorIdFilter` tarkistuksesta ja kaatoi `AuthorityRecommend` sivupohjan.
Sivupohjan muutos ei ole pakollinen, mutta selkeyttää koodia keskeyttämällä heti kun suosituksia ei ole saatavissa.
=> Properly detect active author-id facet

themes/finna2/js/finna-layout.js
Deprecated function .load() should be replaced by .trigger('load')
=> Fix loadScripts (jQuery v3 compatibility)

module/Finna/src/Finna/AjaxHandler/GetUserList.php, module/Finna/src/Finna/Form/Form.php, module/Finna/src/Finna/View/Helper/Root/UserListEmbed.php, themes/finna2/js/finna-image-paginator.js, themes/finna2/js/finna-layout.js, themes/finna2/js/finna-userlist-embed.js, themes/finna2/less/finna/search.less, themes/finna2/templates/Helpers/userlist.phtml
Aiemmin Näytä kaikki -nappi toimi ainoastaan kun `view` asetus oli `grid`. PR:n myötä kaikkia view-tyyppejä voi käyttää `showAllLink` asetuksen kanssa.
Testaus kaikilla view-tyypeillä:
```
<?= $this->userlistEmbed(['id' => 123, 'limit' => 3, 'view' => 'grid', 'showAllLink' => true]); ?>
<?= $this->userlistEmbed(['id' => 123, 'limit' => 3, 'view' => 'list', 'showAllLink' => true]); ?>
<?= $this->userlistEmbed(['id' => 123, 'limit' => 3, 'view' => 'condensed', 'showAllLink' => true]); ?>
<?= $this->userlistEmbed(['id' => 123, 'limit' => 3, 'view' => 'compact', 'showAllLink' => true]); ?>
```
Näytä kaikki -napin (ajax-)lataamissa tietueissa pitäisi toimia js:llä initoitavat toiminnot (saatavuustiedot, lisää suosikkeihin, ostoskori jne) samalla tavalla kuin sivun latauksen yhteydessä …
=> [ALLI-6325] Add support for using all view types together with Show All in embedded userlist

module/Finna/src/Finna/Controller/CoverController.php, module/Finna/src/Finna/Cover/Loader.php
Korjauksen jälkeen Firefoxin pitäisi tallentaa ladattu korkearesoluutiokuva tiedostopäätteen kanssa.
Testaus:
/Record/museovirasto_testi.36E2ABC878385708266F884817B09903 > tietuekuva 12 > Lataa kuva -valikosta > Korkearesoluutiokuva
Selaimen pitäisi pyytää tallentamaan tiedosto tiedostopäätteen kanssa: `museovirasto_testi.36E2ABC878385708266F884817B09903_11_original.tif`
=>  Add filename to downloaded highres image.

module/Finna/src/Finna/Form/Form.php
Testaus:
Sähköpostin otsikon tulisi olla "Subject (label-1)" kun valikosta on valittu ensimmäinen optio:
```
emailSubject: Subject (%%library%%)
fields:
- name: library
recipient: true
type: select
options:
- value: email+1@foo.com
label: label-1
- value: email+2@foo.com
label: label-2
label: feedback_choose_library
=> [ALLI-6363] Feedbackforms: fix email subject to use recipient field label

themes/finna2/js/finna-image-paginator.js, themes/finna2/templates/RecordDriver/DefaultRecord/image-rights.phtml, themes/finna2/templates/RecordDriver/DefaultRecord/record-image-popup-information.phtml, themes/finna2/templates/RecordDriver/DefaultRecord/record-image.phtml
Nykyisin tietuesivun kuvien lisenssikentille ajetaan truncate, mikä on hidasta jos kuvia on tarpeeksi paljon (esim 5000). Tässä PR:ssä lisenssikentän truncate initoidaan tietuesivulla ensimmäiselle näkyvissä olevalle lisenssille, ja muille tarvittaessa kun kuvan thumbnailia on klikattu. 
Testaus:
- tietuesivu
- imagePopup
- .... missä muualla ?
=> Postpone truncating record image license text until the field is visible.

module/Finna/src/Finna/Search/Solr/DeduplicationListener.php, module/Finna/src/Finna/Search/Solr/SolrExtensionsListener.php
Continued from: https://github.com/NatLibFi/NDL-VuFind2/commit/fc245c2f5a062b9222346ab2113721b68407f309
Make sure that the query is not a `QueryGroup` before calling `getHandler`.
=> Fix check for id-search to work with advanced search.

themes/finna2/templates/ajax/status-full.phtml
Functionality restored from:
https://github.com/NatLibFi/NDL-VuFind2/commit/c84d5d73f9570ad7d6922364ef0e6d1e20ae3bfd#diff-cf9ded2cadb9d8a2cc9ff27421a7d1c6L60
=> Fix searchresults holdings collapse
